### PR TITLE
WFCORE-3771 WildFly domain port shift fix

### PR DESCRIPTION
**Pull request by zebrik**
Fix for #33

### CODE REVIEW

**Comment by zebrik** [comment]
@honza-kasik please review

**Comment by m-czernek** [comment]
Does this break compatibility with older WF/EAP servers? Doesn't seem like it, just wanted to be sure. 

I'm not sure if it's better to use the double quotes`"`, which enable you String interpolation, but then force you to escape other double quotes, or whether it's better to use single quotes `'`, which do not require escaping double quotes, but force you into string contatenation. I'm fine with either way, but it's something to consider.

Leaving it to @honza-kasik -- wish there was a better solution than string search and replace though :/.

**Comment by zebrik** [comment]
I agree on the search/replace stuff being extremely ugly but IMHO this code doesn't deserve vast refactoring.

**Comment by zebrik** [comment]
Keeping this code backward compatible for older WildFly versions would IMO reduce code readability (yes, because of the current find/replace solution).
Yet for older WildFly versions the user can still use older Noe-core versions.

**Comment by honza-kasik** [comment]
@zebrik Thanks for this fix! Unfortunately, this is a piece of code, nobody touched for a while. I am not sure, if this is used anywhere else than in a JON testsuite. It surely needs replacement by something like Creaper. If it works in your case, let's merge it!

**Comment by zebrik** [comment]
Yes, this works for JON domain tests for WildFly 13 and newer.
@m-czernek is it possible to merge this?

**Comment by m-czernek** [comment]
I have started integration testing. We actually have integration tests for EAP7 domain port shift; I think I'll have to update the integration tests before merging this (however, I'll do that for you).

Please wait until I have further results on this one.

**Comment by m-czernek** [comment]
Thank you, merging. Fix for integration tests will be merged right after this one (#35).

**Pull request merged**
