### PR TITLE
WIP: Nexus connection via https

### PR DESCRIPTION
**Pull request by jan-onderka**
Fixing issue #69

### CODE REVIEW

**Comment by Karm** [comment]
@jan-onderka    That would break HTTP2 test due to cipher suites mismatch. We need: https://github.com/Karm/okhttp/commit/1082895d16169cb8441cd80f408eb79a757fddfc

**Comment by jan-onderka** [comment]
@Karm I didn't notice this PR is still open and push changes. I reverted it.

**Comment by jstourac** [comment]
Changes in this PR are already present in upstream. This should be closed IMHO.

**Comment by AdamKrajcik** [comment]
Closing as already fixed.

**Pull request closed without merging**
