### PR TITLE
BaseOS httpd modules workspace update

### PR DESCRIPTION
**Pull request by jan-onderka**
Previous MR for mod_cluster and mod_jk were tested separately and also I forgot to test them together. This PR is fixing mod_jk workspace.

### CODE REVIEW

**Comment by jan-onderka** [comment]
Both profiles were tested and working as expected.

**Comment by jstefl** [comment]
From code does not imply how this should be used for mod_jk or mod_cluster or anything else.

Please document usage.

**Comment by jan-onderka** [comment]
@jstefl Comment added and also variable names.

**Comment by jstefl** [comment]
LGTM, thank you.

**Pull request merged**
