### PR TITLE
Fix to properly wait for all cmd output to be processed and passed.

### PR DESCRIPTION
**Pull request by jstourac**
As per JavaDoc of Process.consumeProcessOutput() [1], it is not enough
to call Process.waitFor() to be sure all the StdOut and StdErr data are
processed. It is necessary to call Process.waitForProcessOutput() [2] instead.
Unfortunately the latter method is blocking, thus other code changes are
required to achieve desired behaviour.

[1] http://docs.groovy-lang.org/docs/groovy-2.4.8/html/groovy-jdk/java/lang/Process.html#consumeProcessOutput(java.io.OutputStream,%20java.io.OutputStream)
[2] http://docs.groovy-lang.org/docs/groovy-2.4.8/html/groovy-jdk/java/lang/Process.html#waitForProcessOutput(java.io.OutputStream,%20java.io.OutputStream)

### CODE REVIEW

**Comment by m-czernek** [comment]
Assigning @jstefl. Jstourac encountered a fail due to using `Cmd#executeCommandRedirectIO` function, which is incorrect. I suggested to use `Cmd#executeCommandConsumeStreams`, which worked for him. The question remains what to do with `Cmd#executeCommandRedirectIO`. I'd be for removing it, which however requires some changes in the testsuite (and in jstourac's testsuites as well). If we want to fix it, I'll leave the arbitration of the MR to you, or whoever else will be taking over Noe Core.

**Comment by jstourac** [comment]
Just to complete previous comment - there is not required any change in our TS anymore, as we flipped to use `Cmd#executeCommandConsumeStreams` method which works for us now.

Thus question is whether this fix shall be accepted as current method is obviously buggy. Note that Marek has run some `note-tests` with this change and reported no regression. That does not mean there are no :)

Regarding to the question of removing the method completely, I don't know what impact this may have for other people that depend on `noe-core`.

**Comment by m-czernek** [comment]
Sure; I ran the OpenSSL tests which use this method, and found no regressions; the tomcatrpm testsuite that uses it as well I didn't execute due to obvious reasons. As I said, I'd be rather for removing this completely in order to reduce the amount of legacy/duplicate code.

**Comment by jstefl** [comment]
I am going to merge this, because removing the method would require non trivial refactoring in noe-tests.

Thank you.

**Pull request merged**
