### PR TITLE
Remove EWS_VERSION from EAP properties files

### PR DESCRIPTION
**Pull request by jan-onderka**
@honza-kasik @Karm @PaulLodge @mmadzin FYI

### CODE REVIEW

**Comment by jstefl** [comment]
Are we sure that this is OK? There is not connectors testing in play, right?

**Comment by jan-onderka** [comment]
RHEL CI Pass, I will execute Windows as well and update with results.

**Comment by jan-onderka** [comment]
@jstefl Windows CI pass as well. You can check the results of run # 191. All integration tests pass

**Comment by jstefl** [comment]
Thank you

**Pull request merged**
