### PR TITLE
Remove H2WebClient class

### PR DESCRIPTION
**Pull request by sgala**
The class was only used as a hack to test http2
when noe-core could not run with jdk supporting it.

### CODE REVIEW

**Comment by PaulLodge** [comment]
@honza-kasik is this OK for you too

**Comment by sgala** [comment]
Note that I also removed the com.squareup.okhttp3.okhttp dependency, used ony by the H2WebClient class. We were using it internally but it was easily removed. It was also part of a "hack" to enable ALPN when noe-core was not able to run with modern JDKs and no longer needed. If any user of noe-core was "getting" it transitively they will need to either remove the dependency or make it explicit when they upgrade to the noe-core version including this PR.

**Comment by honza-kasik** [comment]
Sorry @PaulLodge , missed the notification. Yeah, the `H2Test` was removed, so there's no other use of `H2WebClient` for us. Thank you!

**Review by AdamKrajcik — APPROVED** [review]
LGTM.

**Comment by PaulLodge** [comment]
@honza-kasik @AdamKrajcik thanks

**Pull request merged**
